### ISSUE TITLE
backend test で jest の ワーニング

### ISSUE THREAD

**Issue by s-xix98** [s-xix98/trc-prot#200]
backend コンテナで make test 実行した時、jest で ワーニングが出る

**Comment by wyoheiii** [comment]
jestのバグっぽい？
https://github.com/jestjs/jest/issues/11354
https://github.com/prisma/prisma/issues/17171
https://github.com/jestjs/jest/pull/13139

'node_modules/jest-worker/build/base/BaseWorkerPool.js
"test": "sed -i -e 's/const FORCE_EXIT_DELAY = 500;/const FORCE_EXIT_DELAY = 7000;/g' ./node_modules/jest-worker/build/base/BaseWorkerPool.js && react-scripts test # See https://github.com/facebook/jest/issues/11354",'

issueに載ってるやつ大体試したけど、jestのソースコードの定数を書き換えるしかwarning消えなかった

**Comment by wyoheiii** [comment]
jestのバグです
